### ISSUE TITLE
ProcessHttpRequestAsync  中请有BUG

### ISSUE THREAD

**Issue by wangrw21** [Mcdull0921/NetTask#1]
如果context.Request 的url 参数中带有 “.” 的话，或者是url值，有？号，有http:// 等，此处都处理不了

 int idx1 = unit.LastIndexOf("#");
if (idx1 > 0) unit = unit.Substring(0, idx1);
int idx2 = unit.LastIndexOf("?");
if (idx2 > 0) unit = unit.Substring(0, idx2);
 int idx3 = unit.LastIndexOf(".");

**Comment by Mcdull0921** [comment]
你具体是需要请求什么样的url？可以发个例子吗

**Comment by Mcdull0921** [comment]
> 如果context.Request 的url 参数中带有 “.” 的话，或者是url值，有？号，有http:// 等，此处都处理不了
> 
> int idx1 = unit.LastIndexOf("#");
> if (idx1 > 0) unit = unit.Substring(0, idx1);
> int idx2 = unit.LastIndexOf("?");
> if (idx2 > 0) unit = unit.Substring(0, idx2);
> int idx3 = unit.LastIndexOf(".");

@wangrw21  你具体是需要请求什么样的url？可以发个例子吗

**Comment by wangrw21** [comment]
比如在修改任务配置参数中填http地址，http地址中带上一些参数有这些符号?#.

**Comment by Mcdull0921** [comment]
修改任务配置改成了post请求，服务端也做了相应处理，应该能解决带#的问题，之前是get请求，感谢反馈
